### PR TITLE
Syntax x samurai/misc week 5

### PR DESCRIPTION
**Pull request by SyntaxXSamurai**
Completed week 05

### CODE REVIEW

**Review by git160915 — DISMISSED** [review]
Approved for merg.  No conflicts found.

**Review by git160915 — APPROVED** [review]
Approve for merge.

**Review by git160915 — APPROVED** [review]
Approve for merge.

**Review by git160915 — APPROVED** [review]
Approved for merge.

**Review by git160915 — DISMISSED** [review]

**Review by git160915 — DISMISSED** [review]

**Review by bdgit00 — DISMISSED** [review]
Approved for merge.

**Pull request closed without merging**
